### ISSUE TITLE
Error when Starting Containers

### ISSUE THREAD

**Issue by rdmn** [ryotayamanaka/oracle-pg#14]
Hello @ryotayamanaka, When executing command "docker-compose up" I get this error:

Building graph-client

Traceback (most recent call last):
  File "compose\cli\main.py", line 67, in main
  File "compose\cli\main.py", line 126, in perform_command
  File "compose\cli\main.py", line 1070, in up
  File "compose\cli\main.py", line 1066, in up
  File "compose\project.py", line 615, in up
  File "compose\service.py", line 362, in ensure_image_exists
  File "compose\service.py", line 1147, in build
compose.service.BuildError: (<Service: graph-client>, {'message': 'dockerfile parse error line 9: unknown instruction: &&'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose\cli\main.py", line 78, in main
TypeError: can only concatenate str (not "dict") to str
[11284] Failed to execute script docker-compose

**Comment by ryotayamanaka** [comment]
Thank you for your feedback.

I have corrected one mistake:
https://github.com/ryotayamanaka/oracle-pg/commit/a38d2f6fd6fec45b7c6ebcd403280e58b1366862

Does this work for the issue?

**Comment by rdmn** [comment]
Yes, it's all good now Thank you @ryotayamanaka
